# Lista de Exercícios 4

Métodos Numéricos para Engenharia - Turma C   
Nome: Vinícius de Castro Cantuária   
Matrícula: 14/0165169

Observações:

0. A lista de exercícios deve ser entregue no moodle da disciplina.
0. A lista de exercícios deve ser respondida neste único arquivo (.ipynb). Responda a cada questão na célula imediatamente abaixo do seu enunciado.
0. Não se esqueça de alterar o nome do arquivo e o cabeçalho acima, colocando seu nome e matrícula.
0. A lista é uma atividade avaliativa e individual. Não será tolerado qualquer tipo de plágio.

In [1]:
# Deixe-me incluir o conjunto de módulos do Python científico para você.
%pylab inline

Populating the interactive namespace from numpy and matplotlib


---

## Questão 01

Para implementar o Método da Eliminação de Gauss, um método analítico para solucionar sistemas lineares, é preciso primeiro gerar uma matriz aumentada, resultado da concatenação da matriz de coeficientes com o vetor de termos independentes. Leia um valor `N`, uma matriz de coeficientes e um vetor de termos independentes de um sistema linear de tamanho `N` e imprima a matriz aumentada gerada.

In [2]:
N = int(input())

A = np.zeros((N,N))
for i in range(N):
        A[i] = [float(x) for x in input().split()]

b = np.array([float(x) for x in input().split()])

G = np.hstack((A, b[:, None]))
print(G)

1
1
1
[[1. 1.]]


---

## Questão 02

O Método da Eliminação de Gauss é um método analítico de resolução de sistemas lineares.

Dado o sistema linear $Ax = b$, onde:

$$
A =
\begin{bmatrix}
13 & 7 & 3 \\
5 & 19 & 1 \\
2 & 11 & 23
\end{bmatrix},\ b =
\begin{bmatrix}
31 \\
17 \\
29
\end{bmatrix}
$$

Encontre a matriz aumentada e calcule a matriz triangular superior utilizando o pivoteamento parcial do Método da Eliminação de Gauss. Não utilize funções prontas, como "`np.linalg.solve()`", para realizar o cálculo. Este exercício não contém entradas.

#### Saída Esperada

```
[[ 13.           7.           3.          31.        ]
 [  0.          16.30769231  -0.15384615   5.07692308]
 [  0.           0.          22.63207547  21.14150943]]
```

In [3]:
A = np.array([[13,  7,  3],
              [ 5, 19,  1],
              [ 2, 11, 23.0]])
b = np.array([31, 17, 29.0])

N = len(b)
G = np.hstack((A, b[:, None]))

for i in range(N-1):
    for j in range(i+1, N):
        G[j,:] -= G[j,i] / G[i,i] * G[i,:]

print(G)

[[13.          7.          3.         31.        ]
 [ 0.         16.30769231 -0.15384615  5.07692308]
 [ 0.          0.         22.63207547 21.14150943]]


---

## Questão 03

O Método da Eliminação de Gauss com pivoteamento completo, também chamado de Método de Gauss-Jordan, é um método analítico utilizado para encontrar a solução de sistemas lineares, mas também pode ser utilizado para para encontrar a inversa de matrizes quadradas não-singulares.

Dado o sistema linear $Ax = b$, onde:

$$
A =
\begin{bmatrix}
13 & 7 & 3 \\
5 & 19 & 1 \\
2 & 11 & 23
\end{bmatrix},\ b =
\begin{bmatrix}
31 \\
17 \\
29
\end{bmatrix}
$$

Utilize o Método de Gauss-Jordan para encontrar o vetor solução do sistema linear acima. Não utilize funções prontas, como "`np.linalg.solve()`", para realizar o cálculo. Este exercício não contém entradas.

#### Saída Esperada

```
[ 1.99666528  0.32013339  0.93413922]
```

In [4]:
A = np.array([[13,  7,  3],
              [ 5, 19,  1],
              [ 2, 11, 23.0]])
b = np.array([31, 17, 29.0])

N = len(b)
G = np.hstack((A, b[:, None]))

for i in range(N):
    G[i] = G[i] / G[i,i]
    for j in range(i+1, N):
        G[j,:] -= G[j,i] * G[i,:]

for i in range(N-1, -1, -1):
    for j in range(i-1, -1, -1):
        G[j,:] -= G[j,i] * G[i,:]

print(G[:,N])

[1.99666528 0.32013339 0.93413922]


---

## Questão 04

O Método de Gauss-Jordan também pode ser utilizado para encontrar a inversa de matrizes quadradas não-singulares. Para isso, é preciso concatenar à matriz de coeficientes, uma matriz identidade ao invés de o vetor de termos independentes.

Utilizando a mesma matriz do exercício acima:

$$
A =
\begin{bmatrix}
13 & 7 & 3 \\
5 & 19 & 1 \\
2 & 11 & 23
\end{bmatrix}
$$

Calcule $A^{-1}$ utilizando o método de Gauss-Jordan. Não utilize funções prontas para realizar o cálculo.

#### Saída Esperada

```
[[ 0.08878699 -0.02667778 -0.01042101]
 [-0.02355148  0.06106711  0.00041684]
 [ 0.00354314 -0.0268862   0.04418508]]
```

In [5]:
N = 3
A = np.array([[13,  7,  3],
              [ 5, 19,  1],
              [ 2, 11, 23.0]])

G = np.hstack((A, np.identity(N)))

for i in range(N):
    G[i] = G[i] / G[i,i]
    for j in range(i+1, N):
        G[j,:] -= G[j,i] * G[i,:]

for i in range(N-1, -1, -1):
    for j in range(i-1, -1, -1):
        G[j,:] -= G[j,i] * G[i,:]

print(G[:,N:])

[[ 0.08878699 -0.02667778 -0.01042101]
 [-0.02355148  0.06106711  0.00041684]
 [ 0.00354314 -0.0268862   0.04418508]]


---

## Questão 05

O Método de Jacobi é um método utilizado para encontrar a solução de sistemas lineares de forma numérica, ou seja, por aproximações sucessivas. Uma condição suficiente para que a solução aproximada convirja para a solução correta do sistema linear é: a matriz de coeficientes do sistema linear deve ser estritamente diagonal dominante. Uma matriz estritamente diagonal dominante satisfaz a seguinte equação:

$$
|a_{ii}| > \sum_{j \neq i}{|a_{ij}|}
$$

Utilizando a mesma matriz dos exercícios acima:

$$
A =
\begin{bmatrix}
13 & 7 & 3 \\
5 & 19 & 1 \\
2 & 11 & 23
\end{bmatrix}
$$

Verifique se ela é uma matriz estritamente diagonal dominante.

#### Saída Esperada

A matriz "A" é uma matriz estritamente diagonal dominante.

## N = 3
A = np.array([[13,  7,  3],
              [ 5, 19,  1],
              [ 2, 11, 23.0]])

D = np.zeros(N)
R = np.zeros(N)
for i in range(N):
    D[i] = abs(A[i,i])
    for j in range(N):
        R[i] += abs(A[i,j]) if i != j else 0

is_diag_dom = True
for i in range(N):
    if D[i] <= R[i]:
        is_diag_dom = False
        break

if is_diag_dom:
    print('A matriz "A" é uma matriz estritamente diagonal dominante.')
else:
    print('A matriz "A" não é uma matriz estritamente diagonal dominante.')

---

## Questão 06

O Método de Jacobi é um método utilizado para encontrar a solução de sistemas lineares de forma numérica, ou seja, por aproximações sucessivas. O método funciona da seguinte forma: dado um sistema linear $Ax = b$, divimos a matriz de coeficientes $A$ em $D+R$, onde $D$ é a matriz diagonal formada pela diagonal principal da matriz $A$, e $R$ é a matriz de resíduos, que é a matriz $A$ com todos os elementos da diagonal principal iguais a zero. A próxima aproximação para $x$, é calculada pela equação:

$$
x^{(novo)} = D^{-1}(b - Rx^{(antigo)})
$$

Utilizando o mesmo sistema linear $Ax = b$ dos exercícios anteriores:

$$
A =
\begin{bmatrix}
13 & 7 & 3 \\
5 & 19 & 1 \\
2 & 11 & 23
\end{bmatrix}, b =
\begin{bmatrix}
31 \\
17 \\
29
\end{bmatrix}
$$

Iniciando pela aproximação `x = np.zeros(3)`, encontre as 10 (dez) primeiras aproximações da solução do sistema linear acima, utilizando o Método de Jacobi. Não utilize funções prontas na implementação deste exercício. Este exercício não contém entradas.

#### Saída Esperada

```
[ 0.  0.  0.]
[ 2.38461538  0.89473684  1.26086957]
[ 1.61186411  0.20084492  0.62559409]
[ 2.13210025  0.43763607  1.0246512 ]
[ 1.91250722  0.27972882  0.86616533]
[ 2.03410787  0.34585782  0.96078124]
[ 1.9766655   0.30887786  0.91858036]
[ 2.00631645  0.32621537  0.94126141]
[ 1.99174678  0.31721875  0.93039122]
[ 1.99909962  0.32162499  0.93596088]
```

In [7]:
A = np.array([[13,  7,  3],
              [ 5, 19,  1],
              [ 2, 11, 23.0]])
b = np.array([31, 17, 29.0])

N = len(b)
x = np.zeros(N)

D = np.zeros(N)
R = np.zeros((N,N))
for i in range(N):
    for j in range(N):
        R[i,j] = A[i,j]

for i in range(N):
    D[i] = 1.0 / A[i,i]
    R[i,i] = 0

x_next = D * (b - R.dot(x[:, None])[:,0])
for i in range(10):
    print(x)
    x = x_next
    x_next = D * (b - R.dot(x[:, None])[:,0])

[0. 0. 0.]
[2.38461538 0.89473684 1.26086957]
[1.61186411 0.20084492 0.62559409]
[2.13210025 0.43763607 1.0246512 ]
[1.91250722 0.27972882 0.86616533]
[2.03410787 0.34585782 0.96078124]
[1.9766655  0.30887786 0.91858036]
[2.00631645 0.32621537 0.94126141]
[1.99174678 0.31721875 0.93039122]
[1.99909962 0.32162499 0.93596088]


---

## Questão 07

Questões criadas para treinar a utilização da biblioteca "numpy" para manipulação de matrizes. Resolva os exercícios abaixo.

**7.1.** Declare uma matriz `A` de tamanho `3x4` utilizando a função `np.array()` com quaisquer valores e, em seguida, imprima-a.

In [8]:
A = np.array([[13,  7,  3, 4],
              [ 5, 19,  1, 4],
              [ 2, 11, 23.0, 6]])
print(A)

[[13.  7.  3.  4.]
 [ 5. 19.  1.  4.]
 [ 2. 11. 23.  6.]]


**7.2.** Utilizando a matriz definida acima, agora imprima sua transposta.

In [9]:
print(A.T)

[[13.  5.  2.]
 [ 7. 19. 11.]
 [ 3.  1. 23.]
 [ 4.  4.  6.]]


**7.3.** Imprima toda a segunda linha da matriz $A$ original definida no item 7.1.

In [10]:
print(A[1,:])

[ 5. 19.  1.  4.]


**7.4.** Imprima a segunda e a terceira colunas da segunda linha da matriz transposta $A^T$ gerada no item 7.2.

In [11]:
print(A.T[1,1:3])

[19. 11.]


**7.5.** Imprima o seguinte produto matricial: $AA^T$.

In [12]:
print(A.dot(A.T))

[[243. 217. 196.]
 [217. 403. 266.]
 [196. 266. 690.]]


---

## Questão 08

O Método de Gauss-Seidel é um método numérico utilizado para encontrar a solução de sistemas lineares. O método funciona da seguinte forma: dado um sistema linear $Ax = b$, divimos a matriz de coeficientes $A$ em $L_*+U$, onde $L_*$ é uma matriz triangular inferior formada pelos elementos da diagonal principal e abaixo da diagonal principal da matriz $A$, e $U$ é uma matriz triangular superior formada pelos elementos estritamente acima da diagonal princiapl da matriz $A$. $x$ é calculado iterativamente da forma:

$$
x^{(k+1)} = L_*^{-1}(b - Ux^{(k)})
$$

Utilizando o mesmo sistema linear abaixo:

$$
A =
\begin{bmatrix}
13 & 7 & 3 \\
5 & 19 & 1 \\
2 & 11 & 23
\end{bmatrix},\ b =
\begin{bmatrix}
31 \\
17 \\
29
\end{bmatrix}
$$

Iniciando pela aproximação `x = np.zeros(3)`, encontre as 10 (dez) primeiras aproximações da solução do sistema linear, utilizando o Método de Gauss-Seidel. Não utilize funções prontas na implementação deste exercício. Este exercício não contém entradas.

#### Saída Esperada

```
[ 0.  0.  0.]
[ 2.38461538  0.89473684  1.26086957]
[ 1.61186411  0.20084492  0.62559409]
[ 2.13210025  0.43763607  1.0246512 ]
[ 1.91250722  0.27972882  0.86616533]
[ 2.03410787  0.34585782  0.96078124]
[ 1.9766655   0.30887786  0.91858036]
[ 2.00631645  0.32621537  0.94126141]
[ 1.99174678  0.31721875  0.93039122]
[ 1.99909962  0.32162499  0.93596088]
```

---

## Questão 09

Na mesma linha das questões 06 e 08, utilize os Métodos de Jacobi e Gauss-Seidel para encontrar a solução do sistema abaixo:

$$
A =
\begin{bmatrix}
13 & 7 & 3 \\
5 & 19 & 1 \\
2 & 11 & 23
\end{bmatrix},\ b =
\begin{bmatrix}
31 \\
17 \\
29
\end{bmatrix}
$$

Iniciando pela aproximação `x = np.zeros(3)`. Mostre a primeira aproximação $x^k$ tal que nenhuma das diferenças absolutas $|x_i^k - x_i^{k-1}|$ sejam maiores que $10^{-8}$. Mostre também a quantidade de iterações necessárias e o vetor de resíduos ($e = Ax^k - b$) encontrado, para ambos os métodos.

#### Saída Esperada

```
Método de Jacobi: 27 iterações
x =  [1.99666527 0.32013339 0.93413922]
e =  [-9.07208886e-08 -8.03053837e-08 -1.20908751e-07] 

Método de Gauss-Seidel: 9 iterações
x =  [1.99666528 0.32013339 0.93413922]
e =  [ 4.54047218e-08 -1.17981358e-09  0.00000000e+00]
```